trigger:
- main

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

pool:
  name: automation-agent-sebas

stages:

# =========================
# CI - API TESTS
# =========================
- stage: CI_API
  displayName: 'CI - API Tests'
  jobs:
  - job: API_Tests
    displayName: 'Execute API Automation'
    steps:
    - checkout: self
      clean: true

    - task: PowerShell@2
      displayName: 'Run API Tests'
      inputs:
        targetType: 'inline'
        script: |
          cd "$(Build.SourcesDirectory)\RetoApiTest"
          .\gradlew.bat clean test

# =========================
# CI - WEB TESTS
# =========================
- stage: CI_WEB
  displayName: 'CI - Web Tests'
  dependsOn: CI_API
  condition: succeededOrFailed()
  jobs:
  - job: Web_Tests
    displayName: 'Execute Web Automation'
    steps:
    - checkout: self
      clean: true

    - task: PowerShell@2
      displayName: 'Run Web Tests'
      inputs:
        targetType: 'inline'
        script: |
          cd "$(Build.SourcesDirectory)\RetoAutomatizacionWeb"
          .\gradlew.bat clean test aggregate --continue

# =========================
# CD - PUBLISH SERENITY REPORT
# =========================
- stage: CD_REPORTS
  displayName: 'CD - Publish Serenity Report'
  dependsOn:
    - CI_API
    - CI_WEB
  condition: always()
  jobs:
  - job: Publish_Reports
    displayName: 'Publish Serenity Report'
    steps:
    - checkout: self
      clean: false

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Serenity HTML Report'
      inputs:
        targetPath: '$(Build.SourcesDirectory)\RetoAutomatizacionWeb\build\serenity'
        artifactName: 'serenity-report'
      condition: always()