trigger:
- main

pool:
  name: automation-agent-sebas

steps:
- checkout: self

# ---------- API TESTS ----------
- script: |
    echo ===== RUNNING API TESTS =====
    cd %BUILD_SOURCESDIRECTORY%\RetoApiTest
    .\gradlew.bat clean test
  displayName: 'Run API Tests (RetoApiTest)'

# ---------- WEB SCREENPLAY ----------
- script: |
    echo ===== RUNNING SCREENPLAY WEB TESTS =====
    cd %BUILD_SOURCESDIRECTORY%\BaseWebScreenPlay
    .\gradlew.bat clean test
  displayName: 'Run Web Screenplay Tests'

# ---------- WEB AUTOMATIZACION ----------
- script: |
    echo ===== RUNNING WEB AUTOMATION TESTS =====
    cd %BUILD_SOURCESDIRECTORY%\RetoAutomatizacionWeb
    .\gradlew.bat clean test
  displayName: 'Run Web Automation Tests'