#
#Mon Mar 16 23:51:25 COT 2026
acceptInsecureCerts=false
browserName=chrome
goog\:chromeOptions={args\=[start-maximized, test-type, no-sandbox, lang\=es, disable-popup-blocking, disable-download-notification, ignore-certificate-errors, allow-running-insecure-content, disable-translate, always-authorize-plugins, disable-extensions, disable-notifications, incognito, start-maximized, test-type, no-sandbox, lang\=es, disable-popup-blocking, disable-download-notification, ignore-certificate-errors, allow-running-insecure-content, disable-translate, always-authorize-plugins, disable-extensions, disable-notifications, incognito, remote-allow-origins\=*], extensions\=[]}
